### ISSUE TITLE
Add namespacing

### ISSUE THREAD

**Issue by msiebuhr** [msiebuhr/ucs#11]
It is generally sane to use a separate cache-server per project (and Unity version - [citation needed]).

Instead of the currently required way of running a process per cache-server, we should add name-spacing, so the same cache-server can serve many different ports from the same cache (and keep them from poisoning each other).

 * PRO: We'd have simpler server-administration.
 * PRO: Shared GC. Old stuff from inactive builds would be discarded sooner.
 * CON: Single point of failure.
 * CON: Old projects will be wiped, making re-builds potentially very slow.

Practically speaking, I think it'd be done with running it as

    ucs -ns project-one:8125 -ns project-two:8127 ...

or

    ucs -listen project-one:8125,project-two:8127,...

Internally, the server would either communicate namespaces with parameters or through known context variables - and then start up multiple `ucs.Server` with the same back-end attached.

For the file-system back-end, I think the folder structure should be something along the lines of

    $BASEDIR/<namespace>/UU/UUID-HASH.type

**Comment by msiebuhr** [comment]
Unity recommendations at https://github.com/Unity-Technologies/unity-cache-server/issues/50#issuecomment-413854421

**Comment by stephen-palmer** [comment]
I have proposed namespacing internally, but it's unlikely to be implemented mainly because development effort is focused on the next iteration of the asset database, which also includes a more sophisticated cache server. The big sticking point is there is no identifiable data coming from the client (Editor) in order to act on, so it would require a change to Unity and backporting in order to make it useful to anyone that currently needs it.

At the end of the day, though, namespacing would just be a band-aid to the root problem of asset importers changing without version increments that would otherwise force hashes to change. We need to improve testing around the importers to ensure versions are incremented when changes are introduced that will cause outputs to differ from previous versions.

If running multiple cache servers is not practical in your environment, and especially if you have a larg(ish) team, my other suggestion would be to run a single cache server with High Reliability mode enabled, with a reliabilityThreshold of at least 2. This will ensure that data is stable across multiple imports of the same asset before the cache server will propagate a particular asset version to other clients.

**Comment by msiebuhr** [comment]
Nice seeing you here :)

> I have proposed namespacing internally, but it's unlikely to be implemented mainly because development effort is focused on the next iteration of the asset database, which also includes a more sophisticated cache server.

From an operational point of view, I would really appreciate a dumb cache server as possible. HTTP HEAD/GET/PUTs would be at the top of my suggestion list (see https://docs.bazel.build/versions/master/remote-caching.html)

> The big sticking point is there is no identifiable data coming from the client (Editor) in order to act on, so it would require a change to Unity and backporting in order to make it useful to anyone that currently needs it.

True. That is why I'm having one process open a port for each namespace, and then have an internal port -> namespace map to track things.

The cache-server could be made forwards-compatible by accepting eg. `cx<keylen><valuelen><key><value>`, but ignoring what is actually sent. The editor could then implement when convenient in some future version.

> At the end of the day, though, namespacing would just be a band-aid to the root problem of asset importers changing without version increments that would otherwise force hashes to change. We need to improve testing around the importers to ensure versions are incremented when changes are introduced that will cause outputs to differ from previous versions.

I'm not terribly familiar with the editor internals (I don't even have an active license for one, ATM). AFAIK, we are generating some of our meta-files on-the-fly, as not all users (esp. artists) have a Unity-editor, making them show up as new hashes over and over again.

But I guess you're right - having hashes change less would definitely be a nice win :)

> If running multiple cache servers is not practical in your environment, and especially if you have a larg(ish) team, my other suggestion would be to run a single cache server with High Reliability mode enabled, with a reliabilityThreshold of at least 2. This will ensure that data is stable across multiple imports of the same asset before the cache server will propagate a particular asset version to other clients.

Running multiple servers of the 5.x flavor works quite well for us, mostly due to the fact it takes all it's configuration on the command-line. It takes a few minutes to add a file with the right flags and have systemd spin up a new one (ref https://github.com/Unity-Technologies/unity-cache-server/pull/30).

Given that the 6.x takes some arguments *only* on CLI and some *only* in configuration files, it is quite a pain to run multiple servers in a sane way (ref https://github.com/Unity-Technologies/unity-cache-server/pull/44)

Anyway - that doesn't really help on our "internal" problem of generating an awful lot of assets on a one-off basis (I'm working on persuading some higher-ups that it might be a good idea to fix before investing in more caching/build-servers/...)

**Comment by stephen-palmer** [comment]
> I'm not terribly familiar with the editor internals (I don't even have an active license for one, ATM). AFAIK, we are generating some of our meta-files on-the-fly, as not all users (esp. artists) have a Unity-editor, making them show up as new hashes over and over again.
> 
> But I guess you're right - having hashes change less would definitely be a nice win :)

I'm actually saying hashes need to change _more_ - it's because they are not changing when they should be changing that is causing the problems. I'm not quite sure I understand the workflow you're describing for your artists. Are you saying you allow artists to checkin source content (like a .png) into the project root (Assets/), which is only ever imported at build time? i.e., they don't open Unity and therefore do not generate and commit a corresponding .meta file? That's certainly not a recommended workflow.

> Given that the 6.x takes some arguments only on CLI and some only in configuration files, it is quite a pain to run multiple servers in a sane way (ref Unity-Technologies/unity-cache-server#44)

I have a branch in the works to fix this. It also moves almost all of the code in `main.js` and `cleanup.js` into a library with unit tests. Still some more tests to write but it's pretty close. https://github.com/Unity-Technologies/unity-cache-server/tree/improvement/cli-config-parity

**Comment by msiebuhr** [comment]
> I'm actually saying hashes need to change _more_ - it's because they are not changing when they should be changing that is causing the problems.

Aha. That would definitely also be problematic!

> I'm not quite sure I understand the workflow you're describing for your artists. Are you saying you allow artists to checkin source content (like a .png) into the project root (Assets/), which is only ever imported at build time? i.e., they don't open Unity and therefore do not generate and commit a corresponding .meta file? That's certainly not a recommended workflow.

Yes. We have process to make sure this doesn't happen, but things slip over time. We're currently discussing doing automated commits from our build-servers (blank checkout, start+stop Unity editor, commit any changes) to keep things in check.

> > Given that the 6.x takes some arguments only on CLI and some only in configuration files, it is quite a pain to run multiple servers in a sane way (ref [Unity-Technologies/unity-cache-server#44](https://github.com/Unity-Technologies/unity-cache-server/pull/44))
> 
> I have a branch in the works to fix this. It also moves almost all of the code in `main.js` and `cleanup.js` into a library with unit tests. Still some more tests to write but it's pretty close. https://github.com/Unity-Technologies/unity-cache-server/tree/improvement/cli-config-parity

That does look promising!
